2017-12-19 20:19:36,042 [15] ERROR MYBAR.Helper.SyncingWorker - Error in data Inserting in DataBase locallyObject reference not set to an instance of an object.
2017-12-19 20:22:12,515 [27] ERROR MYBAR.Helper.SyncingWorker - Error in data Inserting in DataBase locallyObject reference not set to an instance of an object.
2017-12-19 20:40:17,700 [24] ERROR MYBAR.Services.FatureService - Fail to Save Fature Hyrje from Server An error occurred while updating the entries. See the inner exception for details.
2017-12-19 20:40:22,666 [23] ERROR MYBAR.Services.FatureService - Fail to Save Fature Hyrje from Server An error occurred while updating the entries. See the inner exception for details.
2018-01-16 20:32:21,574 [13] ERROR MYBAR.Helper.SyncingWorker - Fail to Close Table  [Table Id =28] ! response code InternalServerError
2018-01-16 20:32:23,779 [13] ERROR MYBAR.Helper.SyncingWorker - Fail to send Order to server ,data is register in log with Id 311http status=InternalServerError
2018-01-20 12:58:56,730 [14] ERROR MYBAR.Helper.SyncingWorker - Fail to send Order to server ,data is register in log with Id 311http status=InternalServerError
2018-01-20 12:58:57,022 [14] ERROR MYBAR.Helper.SyncingWorker - Fail to Close Table  [Table Id =28] ! response code InternalServerError
2018-01-20 13:00:07,758 [21] ERROR MYBAR.Helper.SyncingWorker - Fail to send Order to server ,data is register in log with Id 312http status=InternalServerError
2018-01-20 13:00:18,289 [15] ERROR MYBAR.Helper.SyncingWorker - Fail to Close Table  [Table Id =28] ! response code InternalServerError
2018-01-20 13:01:49,060 [23] ERROR MYBAR.Helper.SyncingWorker - Fail to send Order to server ,data is register in log with Id 313http status=InternalServerError
2018-01-20 13:03:06,696 [29] ERROR MYBAR.Helper.SyncingWorker - Fail to send Order to server ,data is register in log with Id 314http status=InternalServerError
2018-01-20 13:03:54,034 [31] ERROR MYBAR.Helper.SyncingWorker - Fail to Close Table  [Table Id =31] ! response code InternalServerError
2018-01-20 13:03:57,209 [31] ERROR MYBAR.Helper.SyncingWorker - Fail to Close Table  [Table Id =29] ! response code InternalServerError
2018-06-24 11:19:28,757 [4] ERROR MYBAR.Helper.BackgroundWorker - ============Fail To Save data in Register=============Value cannot be null.
Parameter name: value
2018-06-24 11:19:52,986 [1] ERROR MYBAR.Services.UserService - Fail to get all users The underlying provider failed on Open.
2018-06-24 11:30:47,572 [1] ERROR MYBAR.Services.UserService - Fail to get all users The underlying provider failed on Open.
2018-09-05 13:23:04,118 [1] ERROR MYBAR.Services.UserService - Fail to add users localy Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
2018-09-05 13:23:08,402 [1] ERROR MYBAR.Services.UserService - Fail to add users localy Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
2018-09-05 13:24:45,853 [1] ERROR MYBAR.Services.UserService - Fail to add users localy Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
2018-09-05 13:25:25,450 [1] ERROR MYBAR.Services.UserService - Fail to add users localy Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
2019-03-28 22:18:00,780 [1] ERROR MYBAR.Services.UserService - Fail to get all users The underlying provider failed on Open.-->System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<Open>b__2()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
ClientConnectionId:9ccf4d9e-37b0-422f-b49e-0c499667bd7d
Error Number:18456,State:1,Class:14
2019-03-28 22:20:13,103 [1] ERROR MYBAR.Services.UserService - Fail to get all users The underlying provider failed on Open.-->System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<Open>b__2()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
ClientConnectionId:d8745109-4ae5-4d0c-b3ae-9edabdcf1076
Error Number:18456,State:1,Class:14
2019-03-28 22:27:42,601 [1] ERROR MYBAR.Services.UserService - Fail to get all users The underlying provider failed on Open.-->System.Data.SqlClient.SqlException (0x80131904): Login failed for user ''.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<Open>b__2()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
ClientConnectionId:1402997c-90dd-4263-9679-2e017d44dff4
Error Number:18456,State:1,Class:14
